### ISSUE TITLE
CIBox naming convention

### ISSUE THREAD

**Issue by Sanchiz** [propeoplemd/cibox#209]
We need write out naming convention that we are using.

**Comment by podarok** [comment]
Drupal related
all the modules and themes live in

- sites/all
- sites/all/modules
- sites/all/modules/contrib
- sites/all/modules/custom
- sites/all/modules/features
- sites/all/modules/patched
- sites/all/modules/patches
- sites/all/themes
- sites/all/themes/contrib
- sites/all/themes/custom

Naming custom modules
=====

PROJECT-SHORTNAME_MODULE-NAME e.g. ```cibox_docs```

Naming custom features
=====

PROJECT-SHORTNAME_MODULE-NAME_feature e.g. ```cibox_docs_feature```

Code sharing
=====

For ability to support code sharing MODULE-NAME should be selected in relation to business logic of the module. It is not good to create modules by abstracting it our of business. All the modules, ejected to drupal.org from our past project were possible to share only because they represents some feature, tied to business. 
Like 
- salespush - pushing data to SalesForce
- acrypt - Asymetric crypt alghoritm
ans so on
It is almost impossible to create reusable module when you'll grab alltogether new features and content types, unrelated to them. Or settings, related to only this project. That's why all settings(features in Drupal world) should be splitted out of the module, tied to. 
Never put logic into Drupal features. If you have a logic - put it into custom module. In the future that module have a chance to become contrib one.

**Comment by Sanchiz** [comment]
I think this is enough for first iteration.

**Comment by podarok** [comment]
Yup, I agree
