### ISSUE TITLE
Incorrect information in the documentation

### ISSUE THREAD

**Issue by DmitryDrozdik** [propeoplemd/cibox#368]
In the documentation page "Requirements" https://github.com/propeoplemd/cibox/wiki/Requirements  I can see that SSD Disk is required, but in reality not.

**Comment by podarok** [comment]
@DmitryDrozdik it is required. Definitely.
Non SSD disk site build ~30 minutes. SSD one - 3 minute.
WIth 30 minutes overall CI flow makes no sense in terms of optimization

**Comment by DmitryDrozdik** [comment]
@podarok in this case make sense describe this, because this information looks like a proposition for better performance only and it does not prohibit to use on the non SSD disk.

**Comment by podarok** [comment]
In terms of the fact @propeoplemd/cibox is not only a tool for developers, but a suite for Company Operations - we can't allow to use non fast configuration. Otherwise - most of the benefits are lost and overall infrastructure becomes security issue for companies, like breaking deadlines.
We can't allow users to believe in marketing data, exposed worldwide like https://ffwagency.com/blog/building-quality-into-drupal-development-workflow and give them permission to ot meet those benefits.
